### ISSUE TITLE
自定义显示密码框的快捷键

### ISSUE THREAD

**Issue by HuNiu-rgp** [JiuLing-zhang/ComputerLock#12]
### 功能描述

如果能加个自定义显示密码框的快捷键的功能就更好了，然后自动锁屏的时间最好能加上自定义或者多几个选项，能选个1小时最好

### 解决方案

如果能加个自定义显示密码框的快捷键的功能就更好了，然后自动锁屏的时间最好能加上自定义或者多几个选项，能选个1小时最好

### 补充说明

工具非常好用，建议作者加个打赏功能，方便我们给您打赏。
最后想咨询下有没有什么方法能限制任务管理器里面关闭这个程序的？我是运行在Windows虚拟机上的，想要避免其他人未经允许，通过任务管理器杀掉程序从而进入到虚拟机里面。

**Comment by JiuLing-zhang** [comment]
锁屏状态下会禁用掉大部分的系统快捷键，也会禁用掉任务管理器。因此这个时候要通过自定义快捷键来激活解锁比较麻烦，因此这个不做修改。

**Comment by JiuLing-zhang** [comment]
子任务已经拆分完成
