### ISSUE TITLE
鼠标会自动跑到左上角去

### ISSUE THREAD

**Issue by HuNiu-rgp** [JiuLing-zhang/ComputerLock#15]
### 问题描述

使用环境：本地 Mac M3
工具：远程软件 Parallels Client
系统：远程虚拟机 Windows 11

问题：在开启ComputerLock的时候，如果屏幕锁定了，**鼠标会一直瞬间移动到左上角**，而且是本地Mac的鼠标都会移动，不是在windows里面，我一直是怀疑的Parallels远程工具，但是我发现把ComputerLock软件关闭之后，鼠标就不再自动移动了。

### 重现步骤

非常感谢作者的付出，请您喝杯咖啡，别嫌少。
![截屏 2024-07-04 16 18 58](https://github.com/JiuLing-zhang/ComputerLock/assets/173266097/e375508a-68aa-4b7a-8beb-6145f09ef16e)

### 操作系统

windows11

### 程序版本

2.1.5

**Comment by JiuLing-zhang** [comment]
感谢支持和认可。
按你的描述，应该是启用了”禁用 Windows 锁屏“功能。
因为 Windows 没有合适的禁用系统锁屏 API，因此程序需要通过移动鼠标来模拟系统处于一个非空闲状态。
![image](https://github.com/JiuLing-zhang/ComputerLock/assets/78294929/79e26d05-e479-4efd-ac71-56c627f20bdf)

**Comment by JiuLing-zhang** [comment]
@HuNiu-rgp 你再确认一下是不是这个原因，如果是的话麻烦把这个问题关闭下

**Comment by HuNiu-rgp** [comment]
好像是的，感谢
