### ISSUE TITLE
WIN11 企业版闪退

### ISSUE THREAD

**Issue by yconlyme** [JiuLing-zhang/ComputerLock#20]
### 问题描述

WIN11 企业版闪退

### 重现步骤

运行程序后，闪退

### 操作系统

WIN11

### 程序版本

2.1.9 最新版

**Comment by JiuLing-zhang** [comment]
> 1. 首次运行时需要安装 .Net8 运行时，下载地址：https://aka.ms/dotnet/8.0/windowsdesktop-runtime-win-x64.exe
> 2. 如果程序无法启动，请检查是否已安装 WebView2 Runtime，（推荐使用【常青引导程序】进行安装，因为独立安装包已经不支持 Windows 7）下载地址：https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download

如果环境没有问题，麻烦看下 **[`Windows` 事件查看器 -> `Windows` 日志 -> 应用程序]** 中是否有报错。

**Comment by yconlyme** [comment]
谢谢 已经解决了  ，锁屏时可以隐藏鼠标吗

**Comment by JiuLing-zhang** [comment]
> 谢谢 已经解决了 ，锁屏时可以隐藏鼠标吗

可以添加，不过这几天太忙，完了加一下。
#21 锁屏时支持隐藏鼠标光标
