### ISSUE TITLE
不定时会卡死

### ISSUE THREAD

**Issue by liuyanantj** [JiuLing-zhang/ComputerLock#8]
### 问题描述

电脑运行一段时间，在没有锁屏的情况下，鼠标会冻结  类似锁屏生效那种  只有休眠之后才能正常

### 重现步骤

正常操作系统后 不定期出现  没有特殊的标志性

### 操作系统

win10

### 程序版本

2.013  2.10都有

**Comment by JiuLing-zhang** [comment]
@liuyanantj 有没有开启“定时锁定”功能？

**Comment by liuyanantj** [comment]
> @liuyanantj 有没有开启“定时锁定”功能？

开启了 空闲时间5分钟锁定  但是期间我还在操作  不是因为到时间了无动作锁定的
表现为个别程序无法点击  开始excel 然后Word  任务管理器  无法点击开关机  我把电脑的电源键设置成休眠  
按休眠之后再启动就能正常点击了

**Comment by JiuLing-zhang** [comment]
> > @liuyanantj 有没有开启“定时锁定”功能？
> 
> 开启了 空闲时间5分钟锁定 但是期间我还在操作 不是因为到时间了无动作锁定的 表现为个别程序无法点击 开始excel 然后Word 任务管理器 无法点击开关机 我把电脑的电源键设置成休眠 按休眠之后再启动就能正常点击了

我测试了下，当定时锁定功能开启的时候，锁屏和解锁的时候确实会导致鼠标操作变卡，极小概率会影响到正常使用的情况下，这个问题我先优化一下，然后实际在看下有没有解决问题。

**Comment by JiuLing-zhang** [comment]
@liuyanantj 使用新版本再测试下。如果还有问题，估计就不是锁屏程序的问题了，建议关闭软件再试试。

**Comment by liuyanantj** [comment]
> 闭软件再试
我试试看  谢谢
